CREATE DATABASE accela_test_db CHARACTER SET 'utf8';

USE accela_test_db;

CREATE TABLE IF NOT EXISTS person (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    first_name NVARCHAR(255) NOT NULL,
    last_name NVARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS address (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    person_id SMALLINT UNSIGNED NOT NULL,
	street NVARCHAR(255) NOT NULL,
    city NVARCHAR(255) NOT NULL,
    state NVARCHAR(255) NOT NULL,
    postal_code NVARCHAR(255) NOT NULL,
	PRIMARY KEY (id),
    CONSTRAINT fk_person_id
		FOREIGN KEY (person_id)
		REFERENCES person(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);